### PR TITLE
Add build script

### LINKED ISSUE #107: RHEL 7 support
Ensure packages can be built on and installed on SL/RHEL/CentOS 7.

ST mentioned installing the apel packages to `/opt/apel`, but this would be a major change in the file layout.

### PR DESCRIPTION
**Pull request by tofu-rocketry**
Resolves  #107.

This PR adds a build script for creating RPMs.

It should be possible to start from a fresh cloud VM instance, follow the guidelines in the comments, and then run this file to build APEL RPMs, on SL/EL 5, 6, and 7.

As part of the review, please test it.

### CODE REVIEW

**Comment by gregcorbett** [comment]
SL6 works, I'll try SL7 next. I cant test SL5 on the cloud though....

**Comment by gregcorbett** [comment]
and by works, I mean it creates RPMs

**Comment by tofu-rocketry** [comment]
Thanks. I'll give it a go on one of our SL5 boxes.

**Comment by gregcorbett** [comment]
SL7 produces RPMs aswell

**Comment by gregcorbett** [comment]
did the SL5 one work?

**Comment by tofu-rocketry** [comment]
Yes, though it does write them to a different directory. Minor worry though.

**Pull request merged**
