### PR TITLE
Refactor load_from_msg

### PR DESCRIPTION
**Pull request by tofu-rocketry**
Another HEPscore supporting refactor.

- Change string splitting and stripping to a simpler list comprehension.
- Replace call to `set_all` to more direct `set_field`.
- Remove explicit string continuation as we can use implicit string continuation in parentheses.

### CODE REVIEW

**Comment by tofu-rocketry** [comment]
Issues with Travis meant I needed to delete branch and re-push to invoke CI.

**Comment by tofu-rocketry** [comment]
Coverage went down a smidge as I removed a covered line.

**Review by Sae126V — APPROVED** [review]
LGTM.  It's down to using x in the loop. You have used it because it is short lived variable and easily readable and accepted by PEP8 if I am NOT wrong.

**Review by RedProkofiev — APPROVED** [review]
Perfectly logical change and stylistically fine, let's ship it

**Pull request closed without merging**
