### PR TITLE
Release 2.0.0 to dev

### PR DESCRIPTION
**Pull request by tofu-rocketry**

### CODE REVIEW

**Review by Sae126V — APPROVED** [review]
LGTM.

**Comment by norealroots** [comment]
Looks good, are we happy with the checks?

**Comment by Sae126V** [comment]
Hmm! codecov got affected when py3 got merged, Tom. 🤒. New lines got introduced (Python specific version like 2.7 code or 3.6 code) and not covered by unit tests, it seems.

**Comment by tofu-rocketry** [comment]
> Looks good, are we happy with the checks?

Yeah. The coverage check is a bit spurious as this release branch doesn't touch any Python code. It looks like Codecov has had an issue pulling out the right diff.

**Comment by norealroots** [comment]
Thanks both! All good then 👍

**Comment by tofu-rocketry** [comment]
> Hmm! codecov got affected when py3 got merged, Tom. 🤒. New lines got introduced (Python specific version like 2.7 code or 3.6 code) and not covered by unit tests, it seems at one go.

Yeah, I did note that some of the coverage went down where we added alternate code paths that weren't tested, but it was fairly minimal at the time.

**Pull request merged**
